const cantadas = [
  "Vamo brincar de quebra cabeça? Você monta e eu encaixo",
  "PARABÉNS, VOCÊ GANHOU UM VALE BEIJO",
  "Se leu tem que beijar!",
  "A copa vai ser no Catar... E a gente, vai se catar quando?",
  "Se o cupido nos visse juntos ele largava a flecha e batia palmas.",
  "Não sou café, mas sou quente, gostoso e te faço ficar acordada a noite toda.",
  "Você gosta de café? Porque café que eu to a gente vai dar um puta casal.",
  "Que tal dar um bom presente pra tua mãe? Tem eu de genro.",
  "Cuida bem da tua mãe, porque do jeito que ta indo daqui a pouco vira a minha sogra.",
  "To com um problema no olho... Não consigo enxergar a gente separado.",
  "Teu sorriso é lindo, o problema é que ta muito longe do meu!",
  "Não sou o Casimiro, mas com o beijo que vou te dar até ele vai ficar sem reação.",
  "Vamos brincar de imitação? Te dou um beijo e você me da outro.",
  "Já pode avisar seu passado que seu futuro é comigo, viu?",
  "Tem um amigo meu que ta afim de você: EU",
  "O que eu preciso pra te beijar agora? Uma atitude minha ou um sorrisinho seu?",
  "Sabe a diferença de você e do espelho? No espelho eu vejo meu reflexo e em você vejo meu futuro.",
  "Aposto um beijo que você vai me dar um fora.",
  "Eu não sou maquiagem, mas quero estar sempre perto do seu rosto.",
  "Não sou o Casimiro, mas prometo reagir a todos os seus stories.",
  "Você deve estar com muita dor nas costas de estar carregando o peso de ser a mulher mais linda daqui.",
];

export default cantadas;
